#Find the location of planning applications

PREFIX plan: <http://data.gmdsp.org.uk/def/council/planning/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

SELECT DISTINCT ?long ?lat
WHERE {
	?application rdf:type plan:PlanningApplication ;
		geo:long ?long ;
		geo:lat ?lat
}
LIMIT 100